import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHeader } from '@/components/PageHeader';
import { LegalBody, LegalSection, LegalList } from '@/components/LegalDoc';
import { fetchSettings } from '@/lib/serverDb';

// Bump this whenever the text below changes — it is the date shown to visitors.
const LAST_UPDATED = 'August 2026';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'The terms that apply when you use the Carson Exports website, its estimates, its AI tools, and its booking features.',
};

export default async function TermsPage() {
  const { contactEmail, contactPhone } = await fetchSettings();
  const email = contactEmail || 'hello@carsonexports.com';

  return (
    <div className="page fade-in">
      <PageHeader
        eyebrow="Terms of Use"
        title="The ground rules for this website."
        subtitle="These terms cover the website itself. Buying a vehicle is governed by the sale agreement you sign with us, not by this page."
      />
      <LegalBody updated={LAST_UPDATED}>
        <LegalSection heading="Using this site">
          <p style={{ margin: 0 }}>
            By browsing this website you agree to these terms. If you don&apos;t agree with them,
            please don&apos;t use the site. We may update these terms; the date at the top shows
            when they last changed.
          </p>
        </LegalSection>

        <LegalSection heading="Vehicle listings are not offers">
          <p style={{ margin: 0 }}>
            We keep our inventory as accurate as we can, but listings on this site are an
            invitation to enquire, not a binding offer to sell. Prices, availability, mileage,
            equipment and photographs can be out of date or contain errors, and a vehicle shown as
            available may already be sold or on hold. Nothing is reserved for you until we confirm
            it in writing, and the final terms of any purchase are the ones in the signed sale
            agreement.
          </p>
        </LegalSection>

        <LegalSection heading="Estimates are estimates">
          <p style={{ margin: 0 }}>
            Several tools on this site produce numbers that are illustrative only and are not
            offers of credit, appraisals, or quotes:
          </p>
          <LegalList items={[
            <>The <strong>payment calculator</strong> and monthly figures shown on listings — these assume a sample interest rate and term and exclude taxes, fees and any lender charges. Your actual payment depends on the lender&apos;s decision.</>,
            <>The <strong>pre-qualification</strong> tool — it does not run a credit check and does not approve you for financing.</>,
            <>The <strong>trade-in valuation</strong> — a rough guide only. A real offer requires us to inspect the vehicle.</>,
            <>The <strong>out-the-door price</strong> estimate — tax and fee amounts are estimated and vary by province and by deal.</>,
          ]}/>
        </LegalSection>

        <LegalSection heading="AI features">
          <p style={{ margin: 0 }}>
            The chat assistant, the AI search, and many vehicle descriptions are generated by
            artificial intelligence. AI can be confidently wrong. Treat anything it tells you about
            a vehicle&apos;s specification, history, condition or price as a starting point, and
            confirm it with our team before you rely on it. Answers from the assistant are not
            professional financial, legal or mechanical advice.
          </p>
        </LegalSection>

        <LegalSection heading="Accounts">
          <p style={{ margin: 0 }}>
            You&apos;re responsible for what happens under your My Garage account and for keeping
            your password to yourself. Give us accurate contact details — we use them to reach you
            about enquiries and appointments. Tell us if you think someone else has access to your
            account. We may suspend an account that is being used to abuse the site.
          </p>
        </LegalSection>

        <LegalSection heading="Appointments and enquiries">
          <p style={{ margin: 0 }}>
            Booking a test drive holds a time slot with us. We&apos;ll confirm it by email, and
            every confirmation includes a link to cancel. We may need to cancel or move a booking —
            if a vehicle sells, for instance — and we&apos;ll email you if that happens. Please
            don&apos;t submit enquiries or bookings under someone else&apos;s name or contact
            details.
          </p>
        </LegalSection>

        <LegalSection heading="Acceptable use">
          <p style={{ margin: 0 }}>Please don&apos;t:</p>
          <LegalList items={[
            'Scrape, copy or republish our listings, photographs or written content for another dealership or listing site.',
            'Submit false enquiries, fake bookings, or automated form submissions.',
            'Try to break, overload, or gain unauthorised access to the site or its admin area.',
            'Use the AI assistant for anything unlawful, abusive, or unrelated to buying a vehicle.',
          ]}/>
        </LegalSection>

        <LegalSection heading="Our content">
          <p style={{ margin: 0 }}>
            The text, photography, guides and branding on this site belong to Carson Exports or the
            people we licensed them from. You&apos;re welcome to share links to our pages. You need
            our written permission to reproduce the content itself.
          </p>
        </LegalSection>

        <LegalSection heading="Links to other sites">
          <p style={{ margin: 0 }}>
            Where we link out — to a lender, a vehicle-history report, or a social account — we
            don&apos;t control those sites and aren&apos;t responsible for their content or their
            privacy practices.
          </p>
        </LegalSection>

        <LegalSection heading="Availability and liability">
          <p style={{ margin: 0 }}>
            We try to keep the site up and accurate, but we provide it as-is and can&apos;t promise
            it will always be available or error-free. To the extent the law allows, we&apos;re not
            liable for losses arising from using the site, from relying on an estimate or an
            AI-generated answer, or from the site being unavailable. Nothing here limits any right
            you have under consumer protection law that cannot be limited.
          </p>
        </LegalSection>

        <LegalSection heading="Governing law">
          <p style={{ margin: 0 }}>
            These terms are governed by the laws of the Province of Nova Scotia and the laws of
            Canada that apply there.
          </p>
        </LegalSection>

        <LegalSection heading="Contact us">
          <p style={{ margin: 0 }}>
            Questions about these terms? Email{' '}
            <a href={`mailto:${email}`} style={{ color: 'var(--teal-2)' }}>{email}</a>
            {contactPhone ? <>, call {contactPhone},</> : ','} or use the{' '}
            <Link href="/contact" style={{ color: 'var(--teal-2)' }}>contact form</Link>. See also our{' '}
            <Link href="/privacy" style={{ color: 'var(--teal-2)' }}>Privacy Policy</Link>.
          </p>
        </LegalSection>
      </LegalBody>
    </div>
  );
}
